name: Deploy to Server

on:
  push:
    branches:
      - html

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/yoursite
            git fetch origin html
            git reset --hard origin/html
            # Optional: restart web server if needed
            # sudo systemctl reload nginx
